"""
Graph 3D visualization routes.

Serves precomputed 3D layout data (binary + JSON) generated by
`lightrag.tools.compute_3d_layout`. Also serves a standalone HTML
viewer page built on Three.js (inspired by RealDeepResearch Galaxy).
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse

from ..utils_api import get_combined_auth_dependency


def create_graph3d_routes(rag, api_key: Optional[str] = None):
    """Create routes for 3D knowledge graph visualization.

    Layout files are expected in ``rag.working_dir``:
      - graph3d_layout.bin     (binary positions + clusters + ids)
      - graph3d_layout_meta.json  (entity metadata + edges)
    """
    router = APIRouter(tags=["graph3d"])
    combined_auth = get_combined_auth_dependency(api_key)

    def _layout_dir() -> Path:
        return Path(rag.working_dir)

    def _bin_path() -> Path:
        return _layout_dir() / "graph3d_layout.bin"

    def _meta_path() -> Path:
        return _layout_dir() / "graph3d_layout_meta.json"

    @router.get("/graph3d/status", dependencies=[Depends(combined_auth)])
    async def graph3d_status():
        """Return whether the 3D layout has been computed."""
        bin_exists = _bin_path().exists()
        meta_exists = _meta_path().exists()
        result = {
            "layout_computed": bin_exists and meta_exists,
            "binary_file": bin_exists,
            "metadata_file": meta_exists,
        }
        if meta_exists:
            try:
                import json
                meta = json.loads(_meta_path().read_text(encoding="utf-8"))
                result["entity_count"] = meta.get("entity_count", 0)
                result["edge_count"] = meta.get("edge_count", 0)
                result["cluster_count"] = meta.get("cluster_count", 0)
                result["version"] = meta.get("version", "unknown")
            except Exception:
                pass
        return result

    @router.get("/graph3d/layout.bin", dependencies=[Depends(combined_auth)])
    async def graph3d_layout_bin():
        """Return the binary layout file (positions + clusters + ids)."""
        path = _bin_path()
        if not path.exists():
            raise HTTPException(
                status_code=404,
                detail="3D layout not computed yet. "
                "Run `python -m lightrag.tools.compute_3d_layout` first.",
            )
        return FileResponse(
            path,
            media_type="application/octet-stream",
            headers={"Content-Disposition": "inline"},
        )

    @router.get("/graph3d/layout_meta.json", dependencies=[Depends(combined_auth)])
    async def graph3d_layout_meta():
        """Return the JSON metadata file (entity info + edges)."""
        path = _meta_path()
        if not path.exists():
            raise HTTPException(
                status_code=404,
                detail="3D layout metadata not found.",
            )
        return FileResponse(
            path,
            media_type="application/json",
            headers={"Content-Disposition": "inline"},
        )

    @router.get("/graph3d/viewer", response_class=HTMLResponse, include_in_schema=False)
    async def graph3d_viewer(request: Request):
        """Serve the standalone 3D graph viewer page."""
        viewer_path = Path(__file__).parent.parent / "static" / "graph3d_viewer.html"
        if not viewer_path.exists():
            raise HTTPException(status_code=404, detail="3D viewer page not found.")
        # Inject the API base path so the viewer can find the layout endpoints
        root_path = request.scope.get("root_path", "")
        html = viewer_path.read_text(encoding="utf-8")
        html = html.replace("__API_BASE__", root_path)
        return HTMLResponse(content=html)

    @router.get("/graph3d/insights", dependencies=[Depends(combined_auth)])
    async def graph3d_insights():
        """Generate research insights about the knowledge graph."""
        from .cluster_analysis import generate_research_insights
        meta_path = _meta_path()
        if not meta_path.exists():
            raise HTTPException(
                status_code=404,
                detail="3D layout metadata not found.",
            )
        try:
            return generate_research_insights(meta_path)
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Error generating insights: {str(e)}")

    @router.get("/graph3d/clusters", dependencies=[Depends(combined_auth)])
    async def graph3d_clusters():
        """Analyze all clusters and return summaries."""
        from .cluster_analysis import get_all_cluster_analyses
        meta_path = _meta_path()
        if not meta_path.exists():
            raise HTTPException(
                status_code=404,
                detail="3D layout metadata not found.",
            )
        try:
            return {"clusters": get_all_cluster_analyses(meta_path)}
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Error analyzing clusters: {str(e)}")

    @router.get("/graph3d/cluster/{cluster_id}", dependencies=[Depends(combined_auth)])
    async def graph3d_cluster(cluster_id: int):
        """Analyze a specific cluster."""
        from .cluster_analysis import analyze_cluster
        meta_path = _meta_path()
        if not meta_path.exists():
            raise HTTPException(
                status_code=404,
                detail="3D layout metadata not found.",
            )
        try:
            return analyze_cluster(meta_path, cluster_id)
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Error analyzing cluster: {str(e)}")

    return router
